//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public long Numero { get; set; }
        public long Saldo { get; set; }
        public long IDCliente { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
